### ISSUE TITLE
Error: Connect URI is wrong

### ISSUE THREAD

**Issue by ridzafauzi** [CorpGlory/csv2influx#50]
Hi,
I got this error when trying to import the csv file

root@foxy-01:/home/csv2influx# csv2influx --c csv2influx.conf.json test.csv
Reading csv2influx.conf.json
ok
checking format
ok
lines count:8
Connecting to http://user:pwd@127.0.0.1:8086
Error: Connect URI is wrong, eg: http://user:pass@localhost:port,anotherhost:port,yetanother:port/mydatabase
    at new Client (/usr/lib/node_modules/csv2influx/node_modules/influxdb-nodejs/lib/client.js:73:13)
    at Promise (/usr/lib/node_modules/csv2influx/importer.js:94:22)
    at new Promise (<anonymous>)
    at Importer._import (/usr/lib/node_modules/csv2influx/importer.js:92:12)
    at Importer.run (/usr/lib/node_modules/csv2influx/importer.js:88:17)
    at importer.countFileLines.then.linesCount (/usr/lib/node_modules/csv2influx/index.js:55:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by rozetko** [comment]
Hey, @budakgigibesi, you forgot to specify database to write
It should be `http://user:pwd@127.0.0.1:8086/database`

**Comment by rozetko** [comment]
@budakgigibesi did it help?
